export const categories = [
    { id: 1, name: 'Унитазы', slug: 'unitaz', icon: '🚽' },
    { id: 2, name: 'Ванны', slug: 'vanna', icon: '🛁' },
    { id: 3, name: 'Смесители', slug: 'smestitel', icon: '🚰' },
    { id: 4, name: 'Аксессуары', slug: 'akksesuar', icon: '🧴' },
    { id: 5, name: 'Мебель', slug: 'mebel', icon: '🚪' },
    { id: 6, name: 'Зеркала', slug: 'oyna', icon: '🪞' },
];

export const products = [
    {
        id: 1,
        name: 'Унитаз компакт "Комфорт"',
        category: 'unitaz',
        price: 850000,
        oldPrice: 950000,
        image: '/images/data/1.png',
        description: 'Компактный унитаз с микролифтом, антибактериальное покрытие',
        inStock: true,
        featured: true,
    },
    {
        id: 2,
        name: 'Унитаз подвесной "Премиум"',
        category: 'unitaz',
        price: 1250000,
        image: '/images/data/2.png',
        description: 'Подвесной унитаз с системой инсталляции, бесшумный слив',
        inStock: true,
    },
    {
        id: 3,
        name: 'Унитаз напольный "Эконом"',
        category: 'unitaz',
        price: 450000,
        image: '/images/data/3.png',
        description: 'Классический напольный унитаз, простой и надежный',
        inStock: true,
    },

    {
        id: 4,
        name: 'Ванна чугунная "Ретро"',
        category: 'vanna',
        price: 2450000,
        oldPrice: 2800000,
        image: '/images/data/4.png',
        description: 'Чугунная ванна, эмалированное покрытие, ножки в комплекте',
        inStock: true,
        featured: true,
    },
    {
        id: 5,
        name: 'Ванна акриловая "Комфорт"',
        category: 'vanna',
        price: 1250000,
        image: '/images/data/5.png',
        description: 'Акриловая ванна с гидромассажем, подсветка',
        inStock: true,
    },
    {
        id: 6,
        name: 'Ванна стальная "Компакт"',
        category: 'vanna',
        price: 650000,
        image: '/images/data/6.png',
        description: 'Стальная ванна, усиленное покрытие, экран в комплекте',
        inStock: false,
    },

    {
        id: 7,
        name: 'Смеситель для ванны "Элегант"',
        category: 'smestitel',
        price: 450000,
        image: '/images/data/7.png',
        description: 'Однорычажный смеситель с душем, керамический картридж',
        inStock: true,
        featured: true,
    },
    {
        id: 8,
        name: 'Смеситель для раковины "Стандарт"',
        category: 'smestitel',
        price: 280000,
        oldPrice: 320000,
        image: '/images/data/7.png',
        description: 'Компактный смеситель для раковины, аэратор',
        inStock: true,
    },
    {
        id: 9,
        name: 'Смеситель для кухни "Профи"',
        category: 'smestitel',
        price: 380000,
        image: '/images/data/7.png',
        description: 'Высокий излив, выдвижной душ, 2 режима',
        inStock: true,
    },

    {
        id: 10,
        name: 'Набор аксессуаров "Стандарт"',
        category: 'akksesuar',
        price: 180000,
        image: '/images/data/10.png',
        description: 'Держатель для полотенец, крючки, мыльница',
        inStock: true,
    },
    {
        id: 11,
        name: 'Полотенцесушитель "Водный"',
        category: 'akksesuar',
        price: 550000,
        image: '/images/data/11.png',
        description: 'Водяной полотенцесушитель, нержавеющая сталь',
        inStock: true,
        featured: true,
    },
    {
        id: 12,
        name: 'Держатель для туалетной бумаги',
        category: 'akksesuar',
        price: 45000,
        image: '/images/data/12.png',
        description: 'Хромированный держатель, легкая установка',
        inStock: true,
    },

    {
        id: 13,
        name: 'Зеркало с подсветкой "Люкс"',
        category: 'oyna',
        price: 650000,
        oldPrice: 750000,
        image: '/images/data/13.png',
        description: 'Зеркало с LED подсветкой, антизапотевание',
        inStock: true,
        featured: true,
    },
    {
        id: 14,
        name: 'Зеркало "Классик"',
        category: 'oyna',
        price: 280000,
        image: '/images/data/14.png',
        description: 'Настенное зеркало, фацет, серебряное покрытие',
        inStock: true,
    },
    {
        id: 15,
        name: 'Зеркало с полкой "Практик"',
        category: 'oyna',
        price: 380000,
        image: '/images/data/15.png',
        description: 'Зеркало с открытой полкой для хранения',
        inStock: true,
    },

    {
        id: 16,
        name: 'Пенал 3-створчатый "Модерн"',
        category: 'play3',
        price: 1250000,
        image: '/images/data/16.png',
        description: 'Высокий пенал с тремя дверцами, система хранения',
        inStock: true,
        featured: true,
    },
    {
        id: 17,
        name: 'Шкаф под раковину "Компакт"',
        category: 'play3',
        price: 580000,
        oldPrice: 650000,
        image: '/images/data/17.png',
        description: 'Тумба с ящиками, влагостойкий ЛДСП',
        inStock: true,
    },
    {
        id: 18,
        name: 'Шкаф пенал "Узкий"',
        category: 'play3',
        price: 780000,
        image: '/images/data/18.png',
        description: 'Узкий пенал для ограниченного пространства',
        inStock: false,
    },
];

export const featuredProducts = products.filter(product => product.featured);