export const categories = [
    { id: 1, name: 'Унитазы', slug: 'unitaz', icon: '🚽' },
    { id: 2, name: 'Ванны', slug: 'vanna', icon: '🛁' },
    { id: 3, name: 'Смесители', slug: 'smestitel', icon: '🚰' },
    { id: 4, name: 'Аксессуары', slug: 'akksesuar', icon: '🧴' },
    { id: 5, name: 'Мебель', slug: 'mebel', icon: '🚪' },
    { id: 6, name: 'Зеркала', slug: 'oyna', icon: '🪞' },
];

export const products = [
    {
        id: 1,
        name: 'Унитаз компакт "Комфорт"',
        category: 'unitaz',
        price: 850000,
        oldPrice: 950000,
        image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1',
        description: 'Компактный унитаз с микролифтом, антибактериальное покрытие',
        inStock: true,
        featured: true,
    },
    {
        id: 2,
        name: 'Унитаз подвесной "Премиум"',
        category: 'unitaz',
        price: 1250000,
        image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea',
        description: 'Подвесной унитаз с системой инсталляции, бесшумный слив',
        inStock: true,
    },
    {
        id: 3,
        name: 'Унитаз напольный "Эконом"',
        category: 'unitaz',
        price: 450000,
        image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101',
        description: 'Классический напольный унитаз, простой и надежный',
        inStock: true,
    },

    {
        id: 4,
        name: 'Ванна чугунная "Ретро"',
        category: 'vanna',
        price: 2450000,
        oldPrice: 2800000,
        image: 'https://images.unsplash.com/photo-1564540583246-934409427776',
        description: 'Чугунная ванна, эмалированное покрытие, ножки в комплекте',
        inStock: true,
        featured: true,
    },
    {
        id: 5,
        name: 'Ванна акриловая "Комфорт"',
        category: 'vanna',
        price: 1250000,
        image: 'https://images.unsplash.com/photo-1604709177225-055f99402ea3',
        description: 'Акриловая ванна с гидромассажем, подсветка',
        inStock: true,
    },
    {
        id: 6,
        name: 'Ванна стальная "Компакт"',
        category: 'vanna',
        price: 650000,
        image: 'https://images.unsplash.com/photo-1588854337115-1c67d9247e4d',
        description: 'Стальная ванна, усиленное покрытие, экран в комплекте',
        inStock: false,
    },

    {
        id: 7,
        name: 'Смеситель для ванны "Элегант"',
        category: 'smestitel',
        price: 450000,
        image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7',
        description: 'Однорычажный смеситель с душем, керамический картридж',
        inStock: true,
        featured: true,
    },
    {
        id: 8,
        name: 'Смеситель для раковины "Стандарт"',
        category: 'smestitel',
        price: 280000,
        oldPrice: 320000,
        image: 'https://images.unsplash.com/photo-1595515106864-077d6a6d3c4b',
        description: 'Компактный смеситель для раковины, аэратор',
        inStock: true,
    },
    {
        id: 9,
        name: 'Смеситель для кухни "Профи"',
        category: 'smestitel',
        price: 380000,
        image: 'https://images.unsplash.com/photo-1582582429416-8a9a8c19d3c8',
        description: 'Высокий излив, выдвижной душ, 2 режима',
        inStock: true,
    },

    {
        id: 10,
        name: 'Набор аксессуаров "Стандарт"',
        category: 'akksesuar',
        price: 180000,
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
        description: 'Держатель для полотенец, крючки, мыльница',
        inStock: true,
    },
    {
        id: 11,
        name: 'Полотенцесушитель "Водный"',
        category: 'akksesuar',
        price: 550000,
        image: 'https://images.unsplash.com/photo-1604709177263-3b4a8b2ddb3f',
        description: 'Водяной полотенцесушитель, нержавеющая сталь',
        inStock: true,
        featured: true,
    },
    {
        id: 12,
        name: 'Держатель для туалетной бумаги',
        category: 'akksesuar',
        price: 45000,
        image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952',
        description: 'Хромированный держатель, легкая установка',
        inStock: true,
    },

    {
        id: 13,
        name: 'Зеркало с подсветкой "Люкс"',
        category: 'oyna',
        price: 650000,
        oldPrice: 750000,
        image: 'https://images.unsplash.com/photo-1598300053653-0c3d4a5a9e2e',
        description: 'Зеркало с LED подсветкой, антизапотевание',
        inStock: true,
        featured: true,
    },
    {
        id: 14,
        name: 'Зеркало "Классик"',
        category: 'oyna',
        price: 280000,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        description: 'Настенное зеркало, фацет, серебряное покрытие',
        inStock: true,
    },
    {
        id: 15,
        name: 'Зеркало с полкой "Практик"',
        category: 'oyna',
        price: 380000,
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
        description: 'Зеркало с открытой полкой для хранения',
        inStock: true,
    },

    {
        id: 16,
        name: 'Пенал 3-створчатый "Модерн"',
        category: 'play3',
        price: 1250000,
        image: 'https://images.unsplash.com/photo-1600607687644-c7f34b5e2d4c',
        description: 'Высокий пенал с тремя дверцами, система хранения',
        inStock: true,
        featured: true,
    },
    {
        id: 17,
        name: 'Шкаф под раковину "Компакт"',
        category: 'play3',
        price: 580000,
        oldPrice: 650000,
        image: 'https://images.unsplash.com/photo-1598300188904-6287d52746d4',
        description: 'Тумба с ящиками, влагостойкий ЛДСП',
        inStock: true,
    },
    {
        id: 18,
        name: 'Шкаф пенал "Узкий"',
        category: 'play3',
        price: 780000,
        image: 'https://images.unsplash.com/photo-1600585152915-d208bec867a1',
        description: 'Узкий пенал для ограниченного пространства',
        inStock: false,
    },
];

export const featuredProducts = products.filter(product => product.featured);